sudo: false
language: python
python:
  - "3.6"
install: pip install tox-travis
script:
  - tox
deploy:
  skip_cleanup: true
  provider: script
  script:
    - pip install zappa
    - mkdir -p ~/.aws
    - echo "[zappa-deploy]" >> ~/.aws/credentials
    - echo "aws_access_key_id = "$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
    - echo "aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
    # try to update, if the command fails do the initial deploy
    - zappa update production || zappa deploy production;
  on:
    branch: master
